
Start training the environment...
################
# Epoch 0
################
Stage: Training
Input vector shape: torch.Size([4, 10, 70])
Permuted input vector shape: torch.Size([4, 70, 10])
Expanded game vector shape: torch.Size([4, 128, 10])
Expanded user vector shape: torch.Size([4, 128, 10])
Combined vector shape (should be [batch_size, total_input_dim, seq_length]): torch.Size([4, 326, 10])
Train:   0%|          | 0/2260 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Bella Perel\PycharmProjects\nlp_project_eilam\HumanChoicePrediction\StrategyTransfer.py", line 128, in <module>
    env_model = environments.CNN_env.CNN_env(env_name, config=config)
  File "C:\Users\Bella Perel\PycharmProjects\nlp_project_eilam\HumanChoicePrediction\environments\environment.py", line 38, in __init__
    self.train()
  File "C:\Users\Bella Perel\PycharmProjects\nlp_project_eilam\HumanChoicePrediction\environments\environment.py", line 175, in train
    model_output = self.model(model_vectors)
  File "C:\ProgramData\Anaconda3\envs\Pokemon\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Bella Perel\PycharmProjects\nlp_project_eilam\HumanChoicePrediction\environments\CNN_env.py", line 8, in forward
    data = super().forward(vectors["x"], vectors["game_vector"], vectors["user_vector"])
  File "C:\Users\Bella Perel\PycharmProjects\nlp_project_eilam\HumanChoicePrediction\SpecialCNN.py", line 67, in forward
    assert combined_vec.shape[1] == 198, f"Expected second dimension to be 198 but got {combined_vec.shape[1]}"
AssertionError: Expected second dimension to be 198 but got 326